name: OMS_API CI_CD 🚀

on:
  workflow_dispatch:
    inputs:
      deploy_approval:
        description: 'Enter "release" to approve deployment'
        required: true
  push:
    branches:
    - main
    - 'OMS*'

permissions:
  id-token: write
  contents: write

env:
  AZURE_WEBAPP_NAME: omswebapi001
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore ./src/API/API.csproj

      - name: Update appsettings.json
        run: |
          echo "Updating appsettings.json with secrets"
          jq '.ConnectionStrings.DefaultConnection = "${{ secrets.OMSDB_CONNECTION_STRING }}"' ./src/API/appsettings.json > tmp.$$.json && mv tmp.$$.json ./src/API/appsettings.json
          jq '.Jwt.Key = "${{ secrets.JWT_SIGNING_KEY }}"' ./src/API/appsettings.json > tmp.$$.json && mv tmp.$$.json ./src/API/appsettings.json
          
      - name: Build
        run: dotnet build ./src/API/API.csproj --configuration Release --no-restore

      # - name: Run tests
      #   run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ./src/API/API.csproj -c Release -o ${{env.DOTNET_ROOT}}/oms-api-app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: oms-api-app
          path: ${{env.DOTNET_ROOT}}/oms-api-app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    if: github.event.inputs.deploy_approval == 'release'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: oms-api-app

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        # slot-name: 'production'
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

